pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                script {
                    sh '''
                    #!/bin/sh
                    npm run build
                    sleep 1
                    npm start &
                    echo $! > .pidfile
                    echo "PID written to .pidfile:"
                    cat .pidfile
                    '''
                }
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                script {
                    sh '''
                    #!/bin/sh
                    echo "Contents of .pidfile:"
                    cat .pidfile

                    # Read the PID from the .pidfile
                    PID=$(cat .pidfile)

                    # Check if the process is running
                    if ps -p $PID > /dev/null
                    then
                        echo "Killing process $PID"
                        kill $PID
                    else
                        echo "Process $PID does not exist"
                    fi
                    '''
                }
            }
        }
    }
}
